name=PolluxS
version=BETA tes v1
author=rii66
maintainer=rii66
sentence=Hot air station core
paragraph=Original station module packaged as an Arduino library.
category=Device Control
architectures=mcu Android flash
depends=Carberus lib 
